---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  ## https://hub.docker.com/u/geerlingguy
  - name: stretch
    groups:
      - family_debian
    children:
      - debian
    image: "geerlingguy/docker-debian9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: buster
    groups:
      - family_debian
    children:
      - debian
    image: "geerlingguy/docker-debian10-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  options:
    diff: true
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
# verifier:
#   name: ansible
# scenario:
#   test_sequence:
#     - dependency
#     - lint
#     - cleanup
#     - destroy
#     - syntax
#     - create
#     - prepare
#     - converge
#     - idempotence
#     - side_effect
#     - verify
#     - cleanup
#     - destroy
#   create_sequence:
#     - dependency
#     - create
#     - prepare
#   check_sequence:
#     - dependency
#     - cleanup
#     - destroy
#     - create
#     - prepare
#     - converge
#     - check
#     - destroy
#   converge_sequence:
#     - dependency
#     - create
#     - prepare
#     - converge
#   destroy_sequence:
#     - dependency
#     - cleanup
#     - destroy
